// 第二批招募试验导入脚本（来源：项目根目录 招募文件2/*.docx）
// 运行：cd app && npx tsx prisma/seed-recruitment-2.ts
import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";

type TrialSeed = {
  slug: string;
  title: string;
  disease: string;
  city: string;
  phase: string | null;
  status: string;
  isPublic: boolean;
  isFeatured: boolean;
  summary: string;
  description: string | null;
  inclusionBrief: string | null;
  exclusionBrief: string | null;
  sponsor: string | null;
  intervention: string | null;
  studyDesign: string | null;
  targetEnrollment: number | null;
  siteName: string | null;
  siteAddress: string | null;
  contactPerson: string | null;
  contactPhone: string | null;
  benefits: string | null;
  followUpPlan: string | null;
  adVersion: string | null;
  adVersionDate: Date | null;
  ethicsApproval: string | null;
  qrcodeUrl: string | null;
};

const trials: TrialSeed[] = [
  {
    slug: "urea-c14-hp-diagnosis-2025",
    title: "尿素[14C]胶囊用于幽门螺杆菌诊断招募",
    disease: "幽门螺杆菌感染",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-70 周岁、需做胃镜检查的人群，参与无锡贝塔医药研发的尿素[14C]胶囊幽门螺杆菌诊断多中心临床研究，检查费用由申办方承担。",
    description:
      "申办方：无锡贝塔医药科技有限公司。\n研究设计：随机、开放、交叉、自身对照、多中心。\n本研究已获国家药品监督管理局许可及本院伦理委员会批准。\n广告为通用模板，具体医院/科室/联系人由运营补充。",
    inclusionBrief:
      "18-70 周岁（含边界）；性别不限；经研究者评估需做胃镜检查；同意签署知情同意书；试验期间使用有效的非药物避孕措施。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "无锡贝塔医药科技有限公司",
    intervention: "尿素[14C]胶囊",
    studyDesign: "随机、开放、交叉、自身对照、多中心",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究相关检查费用由申办方承担",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-11-26"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "urea-c13-hp-shenzhen-2024",
    title: "尿素[13C]呼气试验药盒 Hp 诊断招募（深圳）",
    disease: "幽门螺杆菌感染",
    city: "深圳",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-75 周岁、需做胃镜检查者，参与南方医科大学深圳医院消化内科的尿素[13C]呼气试验药盒 Hp 诊断多中心临床研究，检查费用由申办方承担。",
    description:
      "申办方：深圳市中核海得威生物科技有限公司。\n研究设计：开放、随机、交叉、自身对照、多中心。\n已获国家药品监督管理局许可和本院伦理委员会批准。",
    inclusionBrief: "18-75 周岁（含边界）；性别不限；经评估需做胃镜检查。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "深圳市中核海得威生物科技有限公司",
    intervention: "尿素[13C]呼气试验药盒",
    studyDesign: "开放、随机、交叉、自身对照、多中心",
    targetEnrollment: null,
    siteName: "南方医科大学深圳医院消化内科",
    siteAddress: "广东省深圳市宝安区新湖路 1333 号南方医科大学深圳医院门诊楼 2 楼",
    contactPerson: "陆冰云 / 黄健",
    contactPhone: "18576779296 / 18984246211",
    benefits: "研究相关检查费用由申办方承担",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-04-28"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "benzocaine-condom-premature-qinghai-2024",
    title: "含苯佐卡因天然橡胶胶乳避孕套延长射精潜伏期招募（青海）",
    disease: "原发性早泄",
    city: "西宁",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-45 岁有固定女性伴侣、诊断为原发性早泄的男性，参与青海大学附属医院泌尿外科避孕套延长阴道内射精潜伏期的临床研究。",
    description:
      "申办方：广州万方健医药有限公司。\n本院作为临床试验参加单位。试验产品尚未上市。",
    inclusionBrief:
      "本人及伴侣年龄 18-45 岁；有固定女性性伴侣且关系稳定 ≥ 3 个月；诊断为原发性早泄；本人及伴侣签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "广州万方健医药有限公司",
    intervention: "含苯佐卡因天然橡胶胶乳避孕套",
    studyDesign: "多中心临床试验",
    targetEnrollment: null,
    siteName: "青海大学附属医院泌尿外科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-01-31"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "adipose-msc-localized-scleroderma-pumch-2025",
    title: "人脂肪间充质干细胞注射液治疗局灶性硬皮病招募",
    disease: "局灶性硬皮病",
    city: "北京",
    phase: "I 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-60 岁、头面部和/或四肢斑块状、线型或泛发型局灶性硬皮病患者，参与北京协和医院整形美容外科的干细胞注射液 I 期临床研究，免费提供研究药物及检查。",
    description:
      "申办方：北京瑷格干细胞科技有限公司。\n主要研究者：龙笑（北京协和医院整形美容外科）。\n研究药物为治疗用生物制品 1 类，已取得药物临床试验批准通知书（2023LP02485），并通过协和伦理委员会批准。全国计划招募 17 名患者。",
    inclusionBrief:
      "18-60 岁（含），性别不限；诊断为斑块状、线型或泛发型局灶性硬皮病，病灶局限在头面部和/或四肢；目标病灶处于炎症期或硬化期。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "北京瑷格干细胞科技有限公司",
    intervention: "人脂肪间充质干细胞注射液（局部注射）",
    studyDesign: "安全性、耐受性和初步有效性临床研究",
    targetEnrollment: 17,
    siteName: "中国医学科学院北京协和医院整形美容外科",
    siteAddress: null,
    contactPerson: "张欣爽（临床协调员）/ 黄金（科研助理）",
    contactPhone: "18822767413 / 13391701705",
    benefits: "免费提供研究治疗药物及相关检查",
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2025-09-15"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "crosslinked-ha-nasolabial-jinan-2024",
    title: "注射用交联透明质酸钠凝胶纠正鼻唇沟皱纹招募（广州）",
    disease: "中重度鼻唇沟皱纹",
    city: "广州",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁及以上、鼻唇沟皱纹 WSRS 3-4 级者，参与南方医科大学珠江医院整形美容科的交联透明质酸钠凝胶多中心随机对照临床研究。",
    description:
      "申办方：山东济坤生物制药有限公司。\n本院拟招募 43 位受试者。",
    inclusionBrief:
      "年龄 ≥18 周岁，性别不限；有纠正鼻唇沟皱纹的需求；左右两侧 WSRS 评分为 3 或 4 级；同意研究期间维持现有护肤习惯。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "山东济坤生物制药有限公司",
    intervention: "注射用交联透明质酸钠凝胶",
    studyDesign: "多中心临床研究",
    targetEnrollment: 43,
    siteName: "南方医科大学珠江医院整形美容科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2024-05-07"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "ebv-blvr-copd-wuhan-2025",
    title: "支气管内活瓣肺减容术招募（慢阻肺重度肺气肿）",
    disease: "慢性阻塞性肺疾病（重度肺气肿）",
    city: "武汉",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "40-80 岁、符合 GOLD 标准的慢阻肺非匀质型肺气肿稳定期患者，参与武汉市中心医院呼吸与危重症医学科的支气管内活瓣肺减容术前瞻性、多中心、随机对照确证性临床试验。",
    description:
      "申办方：北京卡迪泰医疗器械科技有限公司。\n研究设计：前瞻性、多中心、随机对照、确证性临床试验。\n活瓣采用医用植入级硅橡胶，可塑造性与延展性好，为目前 BLVR 中唯一具有可逆性的方案。本品种尚未获国家药品监督管理局批准上市。",
    inclusionBrief:
      "40-80 岁（含）；BMI ≤35 kg/m²；15% ≤FEV1%pred ≤45%；TLC/%pred >100%，RV/pred% ≥175%；DLCO/pred% ≥20%。",
    exclusionBrief: "最终是否入选由研究医生判断。",
    sponsor: "北京卡迪泰医疗器械科技有限公司",
    intervention: "支气管内活瓣（EBV）",
    studyDesign: "前瞻性、多中心、随机对照、确证性临床试验",
    targetEnrollment: null,
    siteName: "武汉市中心医院呼吸与危重症医学科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-12-22"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "hcl001-decompensated-cirrhosis-renji-2023",
    title: "HCL001 细胞注射液治疗失代偿期肝硬化招募",
    disease: "失代偿期肝硬化",
    city: "上海",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-75 岁、确诊失代偿期肝硬化的患者，参与上海交通大学医学院附属仁济医院的 HCL001 细胞注射液（同种异体肝细胞）安全性、耐受性和初步有效性探索性临床试验，全国计划招募 9-18 例。",
    description:
      "牵头：上海交通大学医学院附属仁济医院。\n研究药物：HCL001 细胞注射液（同种异体肝细胞）。\n本研究为探索性临床试验。",
    inclusionBrief:
      "18-75 岁（含）；确诊失代偿期肝硬化；未合并肝癌及其他恶性肿瘤；无心肺脑肾等重要脏器严重功能障碍。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "上海交通大学医学院附属仁济医院（牵头）",
    intervention: "HCL001 细胞注射液（同种异体肝细胞）",
    studyDesign: "探索性临床试验",
    targetEnrollment: 18,
    siteName: "上海交通大学医学院附属仁济医院东院",
    siteAddress: "上海市浦东新区浦建路 160 号",
    contactPerson: "孙医生",
    contactPhone: "15121070273 / 15021628183",
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2023-12-05"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "collagen-crowsfeet-dalian-2025",
    title: "胶原蛋白植入剂纠正鱼尾纹招募（大连）",
    disease: "额部动力性皱纹（鱼尾纹）",
    city: "大连",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁及以上、两侧鱼尾纹 WSRS 3-4 级者，参与大连理工大学附属中心医院（大连市中心医院）整形美容科的胶原蛋白植入剂多中心随机对照临床试验。",
    description:
      "申办方：哈尔滨沛奇隆生物制药有限公司。\n研究设计：前瞻性、多中心、随机、平行对照、评估者设盲、非劣效性临床试验。",
    inclusionBrief:
      "年龄 ≥18 周岁，性别不限；盲态评估者现场两侧鱼尾纹 WSRS 3-4 级（两侧评分可不一致）；同意签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "哈尔滨沛奇隆生物制药有限公司",
    intervention: "胶原蛋白植入剂（皮肤填充剂）",
    studyDesign: "前瞻性、多中心、随机、平行对照、评估者设盲、非劣效性",
    targetEnrollment: null,
    siteName: "大连理工大学附属中心医院（大连市中心医院）整形美容科",
    siteAddress: null,
    contactPerson: "王慧",
    contactPhone: "0411-84412001-8332",
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-08-11"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "tcss-dpn-observational-2025",
    title: "TCSS 量表评价糖尿病周围神经病变研究招募",
    disease: "糖尿病周围神经病变",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "16-80 岁 2 型糖尿病或糖尿病周围神经病变患者，参与由安徽雷允上药业发起的多伦多临床评分系统（TCSS）量表评价真实世界多中心、前瞻性、观察性研究，研究相关检查与随访挂号由申办方支出并提供交通补贴。",
    description:
      "申办方：安徽雷允上药业有限公司。\n研究设计：真实世界、多中心、前瞻性、观察性研究。\n两队列：2 型糖尿病周围神经病变队列 / 2 型糖尿病队列。",
    inclusionBrief:
      "DPN 队列：16-80 岁；2 型糖尿病 + 糖尿病周围神经病变；神经传导测定异常；接受规范治疗。糖尿病队列：16-80 岁；诊断为 2 型糖尿病 ≥6 个月。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "安徽雷允上药业有限公司",
    intervention: "观察性研究（无试验药物）",
    studyDesign: "真实世界、多中心、前瞻性、观察性研究",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究相关检查费用、随访挂号由申办方支出；提供一定额度交通补贴。",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-04-11"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "tns-depression-anding-2025",
    title: "无创脑神经刺激器治疗抑郁障碍招募",
    disease: "中度至重度抑郁障碍",
    city: "北京",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-65 岁、DSM-5 诊断为 MDD 且 MADRS ≥22 的成年门诊或住院抑郁症患者，参与首都医科大学附属北京安定医院神经调控科的无创脑神经刺激器前瞻性、多中心、双盲、随机对照优效性临床研究。",
    description:
      "主要研究者：王刚教授（神经调控科）。\n研究设计：前瞻性、多中心、双盲、平行对照、随机分组、优效性。\n本院计划招募 20 例，预计 2026-01 至 2026-12。",
    inclusionBrief:
      "18-65 周岁（含）；DSM-5 MDD 诊断，无精神病性症状；筛选期 MADRS ≥22；基线已使用某种 SSRI 类抗抑郁药 ≥4 周且改善 <25%；入组后至出组前药物种类和剂量保持不变。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "无创脑神经刺激器（多靶点神经调控）",
    studyDesign: "前瞻性、多中心、双盲、平行对照、随机分组、优效性",
    targetEnrollment: 20,
    siteName: "首都医科大学附属北京安定医院神经调控科",
    siteAddress: null,
    contactPerson: "王医助",
    contactPhone: "15668839829",
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2025-12-18"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "strabismus-detector-chaomu-2025",
    title: "斜视检测仪用于斜视度测量招募",
    disease: "斜视",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "6 岁及以上、有斜视度测量需求者，参与超目（辽宁）医疗科技申办的斜视检测仪前瞻性、多中心、自身配对临床试验。",
    description:
      "申办方：超目（辽宁）医疗科技有限公司。\n研究设计：前瞻性、多中心、自身配对临床试验。\n试验产品尚未获得批准上市。",
    inclusionBrief:
      "年龄 ≥6 岁，性别不限；有斜视度测量需求；近 1 个月内未做过相关视觉训练；自愿签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "超目（辽宁）医疗科技有限公司",
    intervention: "斜视检测仪",
    studyDesign: "前瞻性、多中心、自身配对",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-11-20"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "semaglutide-obesity-phase3-pkuph-2025",
    title: "司美格鲁肽注射液治疗肥胖症 III 期招募",
    disease: "肥胖症",
    city: "北京",
    phase: "III 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-75 岁、BMI ≥28 kg/m² 的不合并 2 型糖尿病肥胖症患者，参与北京大学人民医院牵头、全国约 25 家医院开展的司美格鲁肽注射液 III 期多中心、随机、开放、平行、阳性对照临床试验，计划入组 408 例。",
    description:
      "申办方：海南中和药业股份有限公司（方案编号 ZH-SMGLT-III-01）。\n组长单位：北京大学人民医院。\n研究设计：多中心、随机、开放、平行、阳性对照。对照药为原研进口药司美格鲁肽注射液（诺和盈）。\n研究总周期约 46 周（不超过 2 周筛选期 + 44 周治疗期）。",
    inclusionBrief:
      "18-75 周岁（含边界）；BMI ≥28 kg/m²；筛选前 3 个月内体重变化幅度 ≤5%；育龄期采取有效避孕。",
    exclusionBrief: "以研究方案为准；由研究医师评估决定。",
    sponsor: "海南中和药业股份有限公司",
    intervention: "司美格鲁肽注射液（试验组）vs 诺和盈（对照）",
    studyDesign: "多中心、随机、开放、平行、阳性对照 III 期",
    targetEnrollment: 408,
    siteName: "北京大学人民医院（组长单位）",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2025-09-16"),
    ethicsApproval: "已获北京大学人民医院伦理委员会审议批准",
    qrcodeUrl: null,
  },
  {
    slug: "rf-ablation-lowback-ningbo-2025",
    title: "椎基神经射频消融治疗慢性腰背痛招募（宁波）",
    disease: "慢性腰背痛（Modic I/II 型）",
    city: "宁波",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-80 岁、骨骼成熟、慢性腰背痛 ≥6 个月且非手术治疗效果不佳者，参与宁波大学第一附属医院骨科的神经射频消融治疗系统与一次性射频消融电极刀头套管多中心临床试验。",
    description: "研究设计：多中心临床试验。",
    inclusionBrief:
      "18-80 周岁（含），男女不限；慢性 ≥6 个月腰背痛；至少 6 个月非手术治疗效果不佳；L3-S1 至少一个椎体终板 Modic I/II 型；ODI ≥30；VAS ≥4 cm。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "神经射频消融治疗系统 + 一次性射频消融电极刀头套管",
    studyDesign: "多中心临床试验",
    targetEnrollment: null,
    siteName: "宁波大学第一附属医院骨科",
    siteAddress: null,
    contactPerson: "宋老师",
    contactPhone: "15258377334",
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-08-15"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "cs060380-mash-obesity-phase2-2024",
    title: "CS060380 片治疗 MASH 合并肥胖 II 期招募",
    disease: "代谢相关脂肪性肝炎（MASH）合并肥胖",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-65 岁、肝脏脂肪含量 ≥10% 且 BMI ≥30 的 MASH 合并肥胖患者，参与上海瑞金医院牵头、多中心开展的 CS060380 片 II 期随机、双盲、安慰剂对照、平行分组临床研究。",
    description:
      "组长单位：上海交通大学医学院附属瑞金医院。\n临床试验批准通知书编号：2024LP01824。\n研究设计：随机、双盲、安慰剂对照、平行分组 II 期。",
    inclusionBrief:
      "18-65 周岁（含）；肝脏脂肪含量 ≥10%；BMI ≥30 kg/m²；筛选前 3 个月体重变化 ≤5%。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "CS060380 片",
    studyDesign: "随机、双盲、安慰剂对照、平行分组 II 期",
    targetEnrollment: null,
    siteName:
      "安徽医科大学第二附属医院 / 南京市江宁医院 / 河北医科大学第一医院 / 浙江省人民医院 / 浙大医学院附属第二医院 / 广州医科大学附属第三医院 / 宁波大学附属第一医院 / 温州医科大学附属第一医院",
    siteAddress: null,
    contactPerson:
      "胡老师(安徽二附) 15695652552；赵老师(南京江宁) 13792218506；贾老师(河北一院) 15932112506；占老师(浙江人民) 15079474855；周老师(浙二) 15925604709；韩老师(广医三) 13007280353；王老师(宁大一) 18456010616；张老师(温医一) 19101519414",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: null,
    ethicsApproval: "已获国家药品监督管理局批准（2024LP01824）及瑞金医院伦理批准",
    qrcodeUrl: null,
  },
  {
    slug: "hy0902-gout-hyperuricemia-phase2-2024",
    title: "HY-0902 片治疗痛风伴高尿酸血症 II 期招募",
    disease: "痛风伴高尿酸血症",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-75 岁、满足 ACR/EULAR 痛风分类标准、BMI 18-35 的痛风伴高尿酸血症患者，参与 HY-0902 片 vs 非布司他片多中心、随机、双盲、平行对照 II 期临床研究，全国计划招募 120 例。",
    description:
      "药物临床试验批准通知书编号：2024LP00096、2024LP00097。\n研究周期：筛选期 ≤2 周，治疗期 12 周。",
    inclusionBrief:
      "18-75 周岁（含）；满足 2015 ACR/EULAR 痛风分类标准；sUA ≥480 μmol/L（无合并症）或 ≥420 μmol/L 且有至少一种合并症；BMI 18-35。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "HY-0902 片 vs 非布司他片",
    studyDesign: "多中心、随机、双盲、平行对照 II 期",
    targetEnrollment: 120,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "申办方提供研究用治疗药物及相关检查",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-12-27"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "lds-fibromyalgia-phase2-pumch-2025",
    title: "LDS 片治疗纤维肌痛综合征 II 期招募",
    disease: "纤维肌痛综合征",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-75 岁、符合 2016 ACR 纤维肌痛诊断标准且 BMI 18-35 的患者，参与中国医学科学院北京协和医院牵头的 LDS 片（TRPA1/5-HTT/NET 三靶点）II 期多中心临床研究，随访完成可获交通、误工和采血补助，最高约 7300 元。",
    description:
      "牵头：中国医学科学院北京协和医院风湿免疫科（李梦涛）。\n作用靶点：TRPA1（外周）& 5-HTT、NET（中枢），以度洛西汀为基础开发。\n随机分组：LDS 低剂量组 / LDS 高剂量组 / 安慰剂组（1:1:1）。每日一次口服，共 13 周。\n研究周期：筛选期 1 周 + 导入期 1 周 + 治疗期 13 周 + 随访期 4 周，共返院 8-9 次。",
    inclusionBrief:
      "18-75 周岁（含）；符合 2016 ACR 纤维肌痛诊断（WPI ≥7 且 SSS ≥5，或 WPI 4-6 且 SSS ≥9，病程 >3 个月）；BMI 18-35；NRS 疼痛评分 ≥4；导入期 7 天内至少 4 天日 NRS 评分均值 ≥4。",
    exclusionBrief:
      "对度洛西汀或辅料过敏；合并带状疱疹后神经痛、糖尿病周围神经病变等影响疼痛评估的疾病；其他结缔组织病为主要疼痛来源；重度认知障碍/重度抑郁（PHQ-9 ≥20）/精神分裂症/双相障碍；未经治疗的窄角型青光眼；WBC/HGB/PLT 过低；严重肝肾/心脑血管疾病；6 个月内活动性胃肠道疾病；入组前 14 天使用过 MAOIs 或纤维肌痛治疗药物；3 个月内参加过其他临床试验。",
    sponsor: null,
    intervention: "LDS 片（三靶点 TRPA1 + 5-HTT + NET）",
    studyDesign: "多中心、随机、双盲、安慰剂对照 II 期",
    targetEnrollment: null,
    siteName:
      "中国医学科学院北京协和医院 / 广东省人民医院 / 临汾市中心医院 / 东南大学附属中大医院 / 郑州市中心医院 / 十堰市人民医院 / 长治和平医院 / 宁夏人民医院 / 淮南市人民医院 / 温州市人民医院 / 吉林省人民医院 / 河北省人民医院 / 三门峡市中心医院 / 苏州大学附属第二医院 / 马鞍山市人民医院 / 赣州市人民医院 / 南方医大珠江医院 / 甘肃省人民医院 / 山西医大第一医院 / 宁夏医大总医院 / 东莞茶山医院 / 首都医大宣武医院（共 22 家风湿免疫科）",
    siteAddress: null,
    contactPerson: "以各中心风湿免疫科主要研究者为准",
    contactPhone: null,
    benefits:
      "交通补助 200 元/次（约 1800 元）；误工补助 200 元/次（约 1200 元）；稀疏 PK 采血 2400 元或密集 PK 采血 3300 元；安慰剂组完成全程一次性补助 1000 元。",
    followUpPlan:
      "筛选期 1 周（V1）\n导入期 1 周（V2）\n治疗期 13 周（V3-V7，含第 1/5/9/12/13 周）\n随访期 4 周（V8）",
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "benzocaine-condom-premature-nanchang-2024",
    title: "含苯佐卡因天然橡胶胶乳避孕套延长射精潜伏期招募（南昌）",
    disease: "原发性早泄",
    city: "南昌",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-45 岁、诊断为原发性早泄的男性及伴侣，参与南昌市生殖医院泌尿外科含苯佐卡因天然橡胶胶乳避孕套有效性和安全性临床试验。",
    description: "申办方：广州万方健医药有限公司。本院为临床试验参加单位。",
    inclusionBrief:
      "本人及伴侣年龄 18-45 岁；有固定女性伴侣且关系稳定 ≥3 个月；诊断为原发性早泄；本人及伴侣签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "广州万方健医药有限公司",
    intervention: "含苯佐卡因天然橡胶胶乳避孕套",
    studyDesign: "多中心临床试验",
    targetEnrollment: null,
    siteName: "南昌市生殖医院泌尿外科",
    siteAddress: "江西省南昌市湾里区双马石路 597 号",
    contactPerson: "姚主任 / 张医生 / 郑医生",
    contactPhone: "13767103369 / 18100799208 / 18679659096",
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-01-31"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "dangefenotong-dpn-phase3-2024",
    title: "丹葛酚酮胶囊治疗糖尿病周围神经病变 III 期招募",
    disease: "糖尿病周围神经病变（阴虚血瘀证）",
    city: "多中心",
    phase: "III 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-70 岁、2 型糖尿病符合糖尿病周围神经病变西医诊断及中医阴虚血瘀证标准的患者，参与安徽雷允上药业发起的丹葛酚酮胶囊 III 期多中心临床研究；研究药物、检查、随访挂号由申办方支出，并提供交通补贴。",
    description:
      "申办方：安徽雷允上药业有限公司。\n批件号：2018L02595。\n研究背景：已完成多项 II 期临床并纳入 156 例 DPN 阴虚血瘀证患者，显示安全性及疗效趋势。",
    inclusionBrief:
      "18-70 岁（含）；2 型糖尿病 + 糖尿病周围神经病变（病程 ≥6 个月）；神经传导测定异常；符合中医阴虚血瘀证标准；血糖稳定；TCSS 评分 ≥6 分且导入期前后 TCSS 评分改变 <2 分。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "安徽雷允上药业有限公司",
    intervention: "丹葛酚酮胶囊",
    studyDesign: "多中心临床研究 III 期",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究药物、研究相关检查费用、随访挂号由申办方支出；提供一定额度交通补贴。",
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2024-09-09"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "fuqigubengao-kidneyyang-phase3-kunming-2024",
    title: "附杞固本膏治疗肾阳虚证 III 期招募",
    disease: "肾阳虚证",
    city: "昆明",
    phase: "III 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "40-80 岁、符合肾阳虚证诊断的患者，参与云南白药集团与云南省药物研究所联合发起的附杞固本膏 III 期临床研究，研究药物与研究相关检查费用由申办方承担，每次随访交通补贴 150 元（共 600 元）。",
    description:
      "申办方：云南白药集团股份有限公司 / 云南省药物研究所。\n批件号：2016L10230。\n方案编号：BJXL2024055LJ。\n产品：昆明市中医医院院内制剂膏滋剂，成份附子（黑顺片）、枸杞子、肉桂。",
    inclusionBrief:
      "40-80 周岁，性别不限；符合中医肾阳虚证诊断（权重积分 ≥14）；导入期平均每天夜间排尿 ≥3 次，任一晚 ≥2 次；接受生活方式管理；签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "云南白药集团股份有限公司 / 云南省药物研究所",
    intervention: "附杞固本膏",
    studyDesign: "临床研究 III 期",
    targetEnrollment: null,
    siteName: "昆明市中医医院肾内科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究药物、研究相关检查费用、随访诊查费由申办方支出；每次随访 150 元交通补贴，共 600 元。",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-06-03"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "foshou-weian-gastritis-phase2-2025",
    title: "佛手胃安颗粒治疗慢性非萎缩性胃炎 II 期招募",
    disease: "慢性非萎缩性胃炎（肝胃不和证）",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、符合慢性非萎缩性胃炎诊断及中医肝胃不和证辨证的患者，参与全国多家医院开展的佛手胃安颗粒 II 期临床研究。",
    description:
      "产品：佛手胃安颗粒（舒肝和胃、健脾行滞、理气止痛）。\n已取得国家药品监督管理局和本院伦理委员会批准。",
    inclusionBrief:
      "18-65 周岁（含）；符合慢性非萎缩性胃炎 + 肝胃不和证；6 个月内有胃镜检查（必备）；Hp 阴性或根除后复查阴性；导入期上腹部疼痛周平均 NRS ≥3；随机时具备上腹部疼痛。",
    exclusionBrief:
      "慢性萎缩性胃炎、感染性/放射性等特殊类型胃炎；胃镜示胃或十二指肠溃疡、胃息肉（直径 ≥0.5 cm 或数目 >10）或病理示肠化生、上皮内瘤变/恶变；合并其他消化系统器质性病变。",
    sponsor: null,
    intervention: "佛手胃安颗粒",
    studyDesign: "多中心临床研究 II 期",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-09-08"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "divalproex-complex-partial-epilepsy-2024",
    title: "双丙戊酸钠缓释片添加治疗复杂部分性癫痫招募",
    disease: "成人复杂部分性癫痫",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "根据 1981 ILAE 分类确诊为复杂部分性癫痫发作、筛选前稳定使用 1-3 种 AED 的成年患者，参与四川大学华西医院陈蕾教授牵头、全国约 28 家医院开展的双丙戊酸钠缓释片添加治疗临床试验，计划入组 204 例。",
    description:
      "牵头：四川大学华西医院（陈蕾教授）。\n方案编号：YCRF-SBWSN-II-01。\n临床试验批准通知书：2024LP00715、2024LP00716。\n研究药物用于该适应症添加治疗尚未获批上市。",
    inclusionBrief:
      "成人；1981 ILAE 分类确诊复杂部分性癫痫发作；筛选/基线期前 3 个月每月 ≥2 次发作；8 周筛选期发作 ≥8 次且每 4 周 ≥2 次，无发作间隔 >21 天；筛选前稳定使用 1-3 种 AED ≥1 个月（苯巴比妥/苯妥英钠/扑米酮需 ≥3 个月）；非妊娠哺乳，采取有效避孕。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "双丙戊酸钠缓释片（添加治疗）",
    studyDesign: "多中心临床试验",
    targetEnrollment: 204,
    siteName:
      "华西医院 / 北京天坛医院 / 湘雅三医院 / 四川省医科院·省人民 / 安徽医大二院 / 重庆医大二院 / 兰州大学二院 / 吉林大学一院 / 河南省人民 / 青岛大学附属 / 贵州医大附属 / 温州医大一院 / 南昌大学二附 / 遵义医大附属 / 山西医大一院 / 延安大学咸阳医院 / 成都医学院一附 / 蚌埠医大一附 / 深圳市第二人民 / 荆州市第一人民 / 商丘市第一人民 / 南阳医专一附 / 清远市人民 / 郑州人民 等 28 家",
    siteAddress: null,
    contactPerson:
      "李助理(华西)15366428315；靳助理(天坛)19932183982；刘助理(湘雅三)17607341299；李助理(川省人民)18782841785；夏助理(安医二)15956929917；潘助理(重医二)15213546669；寇助理(兰二)17794248187；谢助理/刘助理(吉大一)18743461171/15124442085；赵助理(河南人民)15737891120；杨助理(青大)19861109153；王钦沛(贵医)17585411117；冉助理(温医一)15968839982；张助理(南昌二附)18270807296；杨素/刘红霞(遵医)18286232532/18311660969；刘/李(山医一)18235069451/13363478286；张国勋/李张霞(延大咸阳)18629430340/18629338948；刘/赖(成医一)18502880690/13880198579；周助理(蚌医一)15605178366；胡主任(深圳二院)13554918106；涂强/杨涛(荆州一)18972161443；张主任/李助理(商丘一)15526319884；冯涛(南阳医专一)15638996063；刘助理(清远人民)15920488588；张医生(郑州人民)13526865624",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: new Date("2024-11-18"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "zhibitai-hyperlipidemia-phase2-2024",
    title: "脂必泰胶囊治疗原发性高脂血症 II 期招募",
    disease: "原发性高脂血症（痰瘀互结、气血不利证）",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-75 岁、BMI 18-30、符合原发性高脂血症痰瘀互结气血不利证诊断且 LDL-C ≥3.4、TG ≤4.5 mmol/L 的患者，参与成都地奥九泓制药发起的脂必泰胶囊 II 期多中心临床研究。",
    description:
      "申办方：成都地奥九泓制药厂。\n方案编号：SJTS-20-06-201。\n产品：脂必泰胶囊（山楂、泽泻、白术、红曲），1998 年上市。\n研究设计：随机、双盲、平行对照、多中心 II 期。",
    inclusionBrief:
      "18-75 周岁（含）；18 ≤BMI ≤30；符合原发性高脂血症痰瘀互结气血不利证；3.4 ≤LDL-C、TG ≤4.5 mmol/L；导入期前后两次 LDL-C 差值绝对值 ≤12%。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "成都地奥九泓制药厂",
    intervention: "脂必泰胶囊（增加剂量探索）",
    studyDesign: "随机、双盲、平行对照、多中心 II 期",
    targetEnrollment: null,
    siteName:
      "中南大学湘雅二医院 / 长沙市第四医院 / 成都中医药大学附属医院 / 成都市第二人民医院 / 西南医科大学附属中医医院 / 广东省第二中医院 / 惠州市中心人民医院 / 长春中医药大学附属医院 / 安徽中医药大学第一附属医院 / 河南科技大学第一附属医院 / 郑州市中心医院",
    siteAddress: null,
    contactPerson:
      "吴助理(湘雅二)15973731135；漆助理(长沙四)13206082819；邱助理(成中医)15828727493；雷助理(成都二)13408055831；张助理(西南医大中医)18886375713；邓助理(广东二中)18182064013；翁助理(惠州中心)15767343375；马助理(长春中医大)18443174762；周助理(安中医一)15256613306；王助理(河南科技大一)19588502633；岳助理(郑州中心)18839017312",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "caraway-fd-eps-phase3-kunming-2024",
    title: "复方藏茴香肠溶液体胶囊治疗功能性消化不良-EPS III 期招募",
    disease: "功能性消化不良（上腹痛综合征 EPS）",
    city: "昆明",
    phase: "III 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、符合功能性消化不良上腹痛综合征亚型诊断的患者，参与全国约 20 家医院开展的复方藏茴香肠溶液体胶囊 III 期临床研究。",
    description:
      "申办方：河北爱尔海泰制药有限公司。\n批件号：2008L10123。\n产品：中药新药 1.1 类，含薄荷素油和藏茴香油。已完成 I、II 期。",
    inclusionBrief:
      "18-65 周岁（含）；符合 FD + EPS 亚型诊断；导入期至少 1 项主要症状（中上腹痛、中上腹烧灼感）周平均 ≥2 分；6 个月内三甲胃镜未见异常或仅慢性非萎缩性胃炎。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "河北爱尔海泰制药有限公司",
    intervention: "复方藏茴香肠溶液体胶囊",
    studyDesign: "多中心临床研究 III 期",
    targetEnrollment: null,
    siteName: "昆明医科大学第一附属医院消化内科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits:
      "研究药物、研究相关检查费用、随访挂号由申办方支出；提供一定额度交通补贴。",
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "caraway-fd-pds-phase3-kunming-2024",
    title: "复方藏茴香肠溶液体胶囊治疗功能性消化不良-PDS III 期招募",
    disease: "功能性消化不良（餐后不适综合征 PDS）",
    city: "昆明",
    phase: "III 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、符合功能性消化不良餐后不适综合征亚型诊断的患者，参与全国约 20 家医院开展的复方藏茴香肠溶液体胶囊 III 期临床研究。",
    description:
      "申办方：河北爱尔海泰制药有限公司。\n批件号：2008L10123。\n产品：中药新药 1.1 类，含薄荷素油和藏茴香油。已完成 I、II 期。",
    inclusionBrief:
      "18-65 周岁（含）；符合 FD + PDS 亚型诊断；导入期至少 1 项主要症状（餐后饱胀不适、早饱感）周平均 ≥2 分；6 个月内三甲胃镜未见异常或仅慢性非萎缩性胃炎。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "河北爱尔海泰制药有限公司",
    intervention: "复方藏茴香肠溶液体胶囊",
    studyDesign: "多中心临床研究 III 期",
    targetEnrollment: null,
    siteName: "昆明医科大学第一附属医院消化内科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits:
      "研究药物、研究相关检查费用、随访挂号由申办方支出；提供一定额度交通补贴。",
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "xiaoerreping-uri-phase2-2025",
    title: "小儿热平颗粒治疗儿童急性上呼吸道感染 II 期招募",
    disease: "儿童急性上呼吸道感染（外感风热，卫气同病证）",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "2-14 周岁、符合儿童急性上呼吸道感染诊断及中医外感风热卫气同病证辨证的儿童，参与九华华源药业申办的小儿热平颗粒 II 期多中心临床试验。",
    description:
      "申办方：九华华源药业股份有限公司。\n处方：源自中国中医科学院西苑医院安效先教授临床经验方。\n研究设计：随机、双盲、极低剂量平行对照、多中心 II 期。",
    inclusionBrief:
      "2-14 周岁（含）；符合儿童急性上呼吸道感染西医诊断 + 外感风热卫气同病证中医辨证；筛选时发热病程 ≤48 h；随机入组时腋温 ≥37.5℃；恶风寒/鼻塞/流浊涕/咽红肿痛/喷嚏至少一项为中度或重度；家长与 ≥8 岁患儿签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "九华华源药业股份有限公司",
    intervention: "小儿热平颗粒",
    studyDesign: "随机、双盲、极低剂量平行对照、多中心 II 期",
    targetEnrollment: null,
    siteName:
      "广东省中医院 / 长春中医药大学附属医院 / 湖南中医药大学第一附属医院 / 邵阳学院附属第一医院 / 河南中医药大学第一附属医院 / 河南大学第一附属医院 / 三门峡市中心医院 / 高州市人民医院 / 成都市妇女儿童中心医院",
    siteAddress: null,
    contactPerson:
      "张助理 18826238221 / 刘助理 18319233707（广东省中医院）；曲助理 13844805194（长春中医大附）；张助理 15574816461（湖南中医大一附）；雷助理 19021912343（邵阳学院一附）；林助理 15538354561（河南中医大一附）；闫助理 15737905966（河南大学一附）；占助理 15346575850（三门峡中心）；李助理 13828695307（高州人民）；马助理 18583433634（成都妇女儿童）",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: new Date("2025-05-13"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "dry-eye-multicenter-2025",
    title: "干眼症临床试验多中心招募",
    disease: "干眼症",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "干眼症患者可就近联系全国 11 家临床试验参研医院的研究助理咨询入组。",
    description:
      "本条目为干眼症试验的多中心联系方式表，具体方案、药物或器械、入排标准请咨询各医院助理确认。",
    inclusionBrief: "以各中心具体方案为准。",
    exclusionBrief: "以各中心具体方案为准。",
    sponsor: null,
    intervention: null,
    studyDesign: "多中心",
    targetEnrollment: null,
    siteName:
      "复旦大学附属眼耳鼻喉科医院 / 海南省眼科医院 / 咸阳市第一人民医院 / 成都市第二人民医院 / 甘肃省人民医院 / 通化市中心医院 / 中国医学科学院北京协和医院 / 华中科技大学同济医学院附属协和医院 / 石家庄市人民医院 / 中南大学湘雅二医院 / 浙江省人民医院",
    siteAddress: null,
    contactPerson:
      "黄助理 13636300614（复旦眼耳鼻喉）；黄助理 18889649579（海南眼科）；王助理 17342939946（咸阳一人民）；兰助理 13281018867（成都二人民）；周助理 18894315197（甘肃人民）；李助理 18404350199（通化中心）；王助理 15933680202（协和）；陈助理 15972731349（华中协和）；安助理 17693036814（石家庄人民）；贺助理 18108451868（湘雅二）；杨助理 15561843080（浙江人民）",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: null,
    qrcodeUrl: null,
  },
  {
    slug: "liuhedan-ointment-acute-pancreatitis-phase2-2025",
    title: "六合丹软膏治疗急性胰腺炎腹痛 II 期招募",
    disease: "中重症急性胰腺炎（腹痛）",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、符合中重症急性胰腺炎诊断、腹痛 VAS 3-8 分、病程 ≤14 天的患者，参与成都海禾医药申办、华西医院等多中心开展的六合丹软膏 II 期临床试验。",
    description:
      "申办方：成都海禾医药科技有限公司。\n产品：在四川大学华西医院医疗机构制剂六合丹基础上改良而成的新药，成份含大黄、黄柏、白及、白芷、乌金、乌梅、甘草、薄荷素油、蜂蜜。",
    inclusionBrief:
      "18-65 周岁（含）；符合中重症急性胰腺炎诊断；筛选时及随机入组时均存在腹痛，3 ≤VAS ≤8；病程 ≤14 天。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "成都海禾医药科技有限公司",
    intervention: "六合丹软膏",
    studyDesign: "多中心临床研究 II 期",
    targetEnrollment: null,
    siteName:
      "四川大学华西医院 / 德阳市人民医院 / 上海长海医院 / 南昌大学第二附属医院 / 南昌大学第一附属医院 / 温州医科大学附属第二医院 / 华中科技大学同济医学院附属协和医院 / 成都中医药大学附属医院 / 咸阳市第一人民医院 / 成都市双流区第一人民医院",
    siteAddress: null,
    contactPerson:
      "岑助理 13438829846（华西）；黄助理 17381568030（德阳人民）；袁助理 13681610101（上海长海）；王助理 15338746215 / 王助理 15979182672（南昌二附）；韩助理 / 张助理 15279133647（南昌一附）；吕助理 15068905921（温医二）；成助理 15586883725（华中协和）；侯助理 17302956597（成中医）；王助理 18792614199（咸阳一人民）；张老师 17308059552 / 陈助理 18325214545（双流一人民）",
    contactPhone: null,
    benefits:
      "研究相关检查费用（血常规、生化、凝血、电解质、脂肪酶、淀粉酶、CT/彩超、心电图、育龄女性妊娠试验等）由申办方支付；申办方提供试验用药。西医常规治疗药物及费用由患者承担。",
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "pulse-ablation-oral-leukoplakia-chongqing-2025",
    title: "脉冲消融系统治疗口腔白斑病招募（重庆）",
    disease: "口腔白斑病",
    city: "重庆",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-70 岁、临床和病理确诊的口腔白斑病患者，参与重庆医科大学附属口腔医院口腔黏膜科的脉冲消融系统前瞻性、多中心、随机对照临床试验。",
    description:
      "本院：重庆医科大学附属口腔医院口腔黏膜科。\n已获国家药品监督管理总局中国食品药品检定研究院合格注册检验报告，本院伦理委员会已审查同意。",
    inclusionBrief:
      "18-70 周岁（含）；经临床和组织病理学确诊的口腔白斑病；不伴异常增生或伴轻至中度异常增生；病变分布于颊、舌等相对较平坦部位且明显可见；愿意签署知情同意并接受随访。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "脉冲消融系统 + 一次性使用脉冲消融电极",
    studyDesign: "前瞻性、多中心、随机对照",
    targetEnrollment: null,
    siteName: "重庆医科大学附属口腔医院口腔黏膜科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v2.0",
    adVersionDate: new Date("2025-09-10"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "adm-infraorbital-hollow-pku3-2025",
    title: "脱细胞真皮基质植入剂纠正眶下凹陷招募",
    disease: "眶下凹陷",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁及以上、双侧眶下凹陷 AIHS 2-3 级（中至重度）者，参与北京大学第三医院牵头的脱细胞真皮基质植入剂前瞻性、多中心、随机、无治疗对照、评估者设盲、优效性临床试验。",
    description:
      "牵头：北京大学第三医院。\n参研：陆军军医大学第一附属医院、成都市第二人民医院、南京医科大学第二附属医院、重庆医科大学附属第一医院。",
    inclusionBrief:
      "年龄 ≥18 周岁，性别不限；有改善双侧眶下凹陷需求；双侧眶下凹陷 AIHS 2-3 级（中至重度），两侧评分可不一致；同意研究期间不使用其他相关美容治疗。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "脱细胞真皮基质植入剂",
    studyDesign: "前瞻性、多中心、随机、无治疗对照、评估者设盲、优效性",
    targetEnrollment: null,
    siteName:
      "北京大学第三医院整形外科 / 陆军军医大学第一附属医院整形外科 / 成都市第二人民医院医疗美容科 / 南京医科大学第二附属医院医疗美容科 / 重庆医科大学附属第一医院皮肤科",
    siteAddress:
      "北京海淀区花园北路 49 号；重庆沙坪坝区高滩岩正街 29 号；四川成都庆云南街 10 号；南京鼓楼区中山北路 309 号；重庆渝中区袁家岗友谊路 1 号",
    contactPerson:
      "王老师 15611963586（北医三）；卓老师 15213035531（陆军军医大一附）；周老师 13002590393（南京医大二附）；慕老师 19823388683（重医一）",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获伦理委员会审查批准",
    qrcodeUrl: null,
  },
  {
    slug: "hx15001-uc-phase2a-sysuh6-2025",
    title: "HX15001 注射液治疗中重度溃疡性结肠炎 IIa 期招募",
    disease: "中重度活动性溃疡性结肠炎",
    city: "多中心",
    phase: "IIa 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "18-80 岁、体重 ≥40 kg、确诊中重度活动性溃疡性结肠炎且既往对至少一种系统治疗应答不足的患者，参与中山大学附属第六医院组长的 HX15001 注射液 IIa 期随机、双盲、安慰剂对照临床试验。",
    description:
      "申办方：华深智药生物科技（苏州）有限公司。\n组长：中山大学附属第六医院。\n研究设计：随机、双盲、安慰剂对照 IIa 期。",
    inclusionBrief:
      "18-80 周岁（含）；体重 ≥40 kg；筛选前至少 12 周确诊 UC；改良 Mayo 评分 4-9、Mayo 内镜评分 ≥2；筛选时累及距肛外缘 ≥15 cm；广泛结肠炎 ≥8 年或左半结肠 ≥10 年者需异型增生监测；既往对氨基水杨酸/糖皮质激素/免疫抑制剂/生物疗法/S1P 受体调节剂/JAK 抑制剂至少一种应答不足。",
    exclusionBrief: "以研究方案为准；最终由研究者评估。",
    sponsor: "华深智药生物科技（苏州）有限公司",
    intervention: "HX15001 注射液",
    studyDesign: "随机、双盲、安慰剂对照 IIa 期",
    targetEnrollment: null,
    siteName: "中山大学附属第六医院（组长单位）",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-11-06"),
    ethicsApproval: "已获国家药品监督管理总局及组长单位伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "rf-facial-wrinkle-pkush-2026",
    title: "射频治疗系统改善面部皱纹招募（深圳）",
    disease: "面部皱纹",
    city: "深圳",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、Fitzpatrick 皮肤类型 II-IV、FWES 评分 3-6 分有面部皱纹改善需求者，参与北京大学深圳医院皮肤科的射频治疗系统前瞻性、多中心、随机、阳性平行对照、评估者设盲、非劣效性临床试验，本院拟招募 40 位。",
    description: "申办方：北博（浙江）医疗科技有限公司。",
    inclusionBrief:
      "18-65 岁（含）；Fitzpatrick II-IV 型；面部皱纹 FWES 评分 3-6 分；有面部皱纹改善需求；自愿签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "北博（浙江）医疗科技有限公司",
    intervention: "射频治疗系统",
    studyDesign: "前瞻性、多中心、随机、阳性平行对照、评估者设盲、非劣效性",
    targetEnrollment: 40,
    siteName: "北京大学深圳医院皮肤科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2026-01-10"),
    ethicsApproval: "已获本院临床试验伦理审查委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "vigabatrin-infantile-spasms-2023",
    title: "氨己烯酸口服溶液用散单药治疗婴儿痉挛招募",
    disease: "婴儿痉挛",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: true,
    summary:
      "2-24 月龄、诊断婴儿痉挛且既往未治或治疗无效/复发的婴儿，参与氨己烯酸口服溶液用散单药治疗开放、单臂、前瞻性、多中心上市后临床研究，全国计划招募 57 例。",
    description:
      "方案编号：BOJI2023010DB。\n研究设计：开放、单臂、前瞻性、多中心上市后临床研究。",
    inclusionBrief:
      "2 月龄 ≤年龄 ≤24 月龄；筛选前诊断婴儿痉挛；基线有临床痉挛发作和 EEG 高度失律或 IS 相符的异常；既往未治或治疗无效/复发；eGFR >60 mL/min/1.73 m²；父母/监护人同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "氨己烯酸口服溶液用散（单药）",
    studyDesign: "开放、单臂、前瞻性、多中心上市后临床研究",
    targetEnrollment: 57,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究用药物和非临床常规相关检查免费提供；专门研究人员跟进康复。",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2023-11-23"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "peiqilong-crosslinked-collagen-nasolabial-2025",
    title: "交联胶原蛋白植入剂纠正鼻唇沟招募（沛奇隆）",
    disease: "中重度鼻唇沟皱纹",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁及以上有改善鼻唇沟皱纹需求者，参与哈尔滨沛奇隆生物制药发起的交联胶原蛋白植入剂纠正鼻唇沟皱纹多中心临床试验（招募广告 v1.0 / 2025-07-30，详细入排请咨询参研医院）。",
    description:
      "申办方：哈尔滨沛奇隆生物制药有限公司。\n原广告文件为加密 .doc，文本无法可靠抽取；详细方案、入排标准、参研医院请联系申办方或运营确认。",
    inclusionBrief:
      "年龄 ≥18 周岁，性别不限；有纠正鼻唇沟皱纹需求；WSRS 3-4 级；自愿签署知情同意（以研究方案为准）。",
    exclusionBrief: "以研究方案为准（原广告未提供可提取的排除标准）。",
    sponsor: "哈尔滨沛奇隆生物制药有限公司",
    intervention: "交联胶原蛋白植入剂",
    studyDesign: "多中心临床试验",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-07-30"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "beraprost-pah-wanle-2024",
    title: "贝前列素钠缓释片治疗肺动脉高压招募",
    disease: "肺动脉高压（IPAH / HPAH / CTD-PAH）",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-75 岁、体重 ≥30 kg、WHO 心功能 I-III 级且接受稳定靶向治疗 ≥1 个月的毛细血管前肺动脉高压患者，参与深圳万乐药业申办的贝前列素钠缓释片（开乐德）上市后随机双盲、安慰剂对照临床研究。",
    description:
      "申办方：深圳万乐药业有限公司（药品注册代理）。\n生产方：Toray Industries, Inc（日本东丽）。\n产品：贝前列素钠缓释片（开乐德），2022-07 在中国上市。\n研究设计：安慰剂对照、双盲；试验组 = 背景治疗 + 贝前列素钠，对照组 = 背景治疗 + 模拟剂，1:1。",
    inclusionBrief:
      "18-75 岁（含）；体重 ≥30 kg；6 个月内右心导管符合 2022 ESC/ERS 毛细血管前肺动脉高压（mPAP ≥20，PAWP ≤15，PVR >2 WU）；IPAH / HPAH / CTD-PAH；WHO 功能分级 I-III；基线 6MWD 150-500 m；育龄期女性妊娠试验阴性；接受 1-2 种稳定剂量肺动脉高压靶向治疗 ≥1 个月；CTD-PAH 患者激素/免疫抑制剂入组前 3 个月内剂量稳定或减量期。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "深圳万乐药业有限公司",
    intervention: "贝前列素钠缓释片（开乐德）",
    studyDesign: "随机、双盲、安慰剂对照、上市后临床研究",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.1",
    adVersionDate: new Date("2024-08-22"),
    ethicsApproval: "已获国家药品监督管理局批准及伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "ftz-nafld-phase2-qianhai-2024",
    title: "FTZ 浓缩丸治疗非酒精性肝脂肪变招募",
    disease: "非酒精性肝脂肪变（肝郁脾虚兼痰瘀互结证）",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、符合非酒精性肝脂肪变诊断且 MRI-PDFF >10%、中医肝郁脾虚兼痰瘀互结证辨证的患者，参与深圳前海吉奥申办的 FTZ 浓缩丸临床研究；研究药物与检查由申办方支出，每次随访 200 元交通补贴共 1000 元。",
    description:
      "申办方：深圳前海吉奥健康科技有限公司。\n药物临床试验批准通知书编号：2024LP01212。\n产品：2011 年起为广东药科大学附属第一医院院内制剂（粤药制字 Z20110029），成份含佛手、酒女贞子、盐杜仲、麸炒白术、三七、丹参、大蓟、黄连。",
    inclusionBrief:
      "18-65 周岁（含）；符合非酒精性肝脂肪变西医诊断，MRI-PDFF >10%；符合中医肝郁脾虚兼痰瘀互结证（倦怠乏力、肢体困重、胁肋胀闷、大便不调至少 2 项）；同意签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "深圳前海吉奥健康科技有限公司",
    intervention: "FTZ 浓缩丸",
    studyDesign: "多中心临床研究",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: "研究药物、研究相关检查费用、随访诊查费由申办方支出；每次随访 200 元交通补贴，共 1000 元。",
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2024-08-20"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "wenfei-dingchuan-copd-phase2-2025",
    title: "温肺定喘颗粒治疗慢阻肺稳定期 II 期招募",
    disease: "慢性阻塞性肺疾病稳定期（肺肾气虚兼痰瘀阻肺证）",
    city: "多中心",
    phase: "II 期",
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "40-75 岁、符合慢阻肺诊断（筛选前病程 ≥1 年）、GOLD 评估 E 组、CAT ≥16 的稳定期患者，参与漳州片仔癀药业申办的温肺定喘颗粒 II 期随机、双盲、安慰剂平行对照、剂量探索、多中心临床试验。",
    description:
      "申办方：漳州片仔癀药业股份有限公司。\n处方：老中医李湘远应用 40 余年临床验方。\n研究设计：随机、双盲、安慰剂平行对照、剂量探索、多中心 II 期。",
    inclusionBrief:
      "40-75 周岁（含）；符合慢阻肺诊断，病程 ≥1 年；肺肾气虚兼痰瘀阻肺证辨证；GOLD E 组；筛选前 4 周内未发生 AECOPD 且吸入剂稳定使用 ≥4 周；CAT ≥16。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "漳州片仔癀药业股份有限公司",
    intervention: "温肺定喘颗粒",
    studyDesign: "随机、双盲、安慰剂平行对照、剂量探索、多中心 II 期",
    targetEnrollment: null,
    siteName: null,
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-03-20"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "ruimei-collagen-crowsfeet-guangdong2-2025",
    title: "人 I 型胶原蛋白冻干纤维纠正鱼尾纹招募（广东二）",
    disease: "动力性皱纹（鱼尾纹）",
    city: "广州",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、两侧鱼尾纹 WSRS 3-4 级者，参与广东省第二人民医院整形美容科的人 I 型胶原蛋白冻干纤维前瞻性、多中心、随机、平行对照、评估者设盲、非劣效性临床试验。",
    description: "申办方：深圳市瑞美再生医学技术有限公司。",
    inclusionBrief:
      "18-65 周岁（含）；性别不限；盲态评估者现场两侧鱼尾纹 WSRS 3-4 级（两侧评分可不一致）；同意签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "深圳市瑞美再生医学技术有限公司",
    intervention: "人 I 型胶原蛋白冻干纤维",
    studyDesign: "前瞻性、多中心、随机、平行对照、评估者设盲、非劣效性",
    targetEnrollment: null,
    siteName: "广东省第二人民医院整形美容科",
    siteAddress: null,
    contactPerson: null,
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: "v1.0",
    adVersionDate: new Date("2025-11-06"),
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "kexing-recombinant-collagen-forehead-2025",
    title: "重组型人源化胶原蛋白冻干纤维纠正额部动力性皱纹招募",
    disease: "额部动力性皱纹（眉间纹、额头纹、鱼尾纹）",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁以上、有至少两项额部动力性皱纹（眉间纹 / 额头纹 / 鱼尾纹）改善需求且严重程度为中至重度者，参与多中心开展的重组型人源化胶原蛋白冻干纤维前瞻性、多中心、随机、阳性平行对照、评估者设盲、非劣效性临床研究。",
    description: null,
    inclusionBrief:
      "年龄 ≥18 周岁；性别不限；寻求额部动力性皱纹纠正（眉间纹 / 额头纹 / 鱼尾纹，至少两项）；至少两项皱纹严重程度为 3 级或 4 级（鱼尾纹两侧可不一致但均为中重度）；同意不采取影响皮肤质量措施或改变护肤习惯。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "重组型人源化胶原蛋白冻干纤维（面部真皮组织填充注射）",
    studyDesign: "前瞻性、多中心、随机、阳性平行对照、评估者设盲、非劣效性",
    targetEnrollment: null,
    siteName:
      "广东省第二人民医院 / 深圳市前海蛇口自贸区医院 / 汕头大学医学院第二附属医院 / 大连理工大学附属中心医院 / 首都医科大学附属北京积水潭医院 / 长沙市第三医院",
    siteAddress: null,
    contactPerson:
      "涂助理 18898682293（广东二）；洪助理 15118174371（前海蛇口）；郭助理 13417118685（汕大二附）；王老师 0411-84412001-6332（大连中心）；赵助理 18518355664（积水潭）；雷助理 15673547728（长沙三）",
    contactPhone: null,
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
  {
    slug: "yuanxiang-ha-complex-skinbooster-2025",
    title: "注射用透明质酸钠复合溶液改善皮肤状态招募（水光针）",
    disease: "面部皮肤状态（皮肤干燥、肤色暗沉）",
    city: "多中心",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18-65 岁、面部皮肤干燥肤色暗沉、Fitzpatrick II-IV 型者，参与广东省第二人民医院牵头的注射用透明质酸钠复合溶液（水光针）多中心临床试验，免费提供研究治疗器械及相关检查、主任医师面诊、随访路程补助、临床试验保险。",
    description:
      "牵头：广东省第二人民医院。\n参研：首都医科大学附属北京潞河医院、广州医科大学附属第二医院、长沙市第三医院、中山大学附属第一医院。",
    inclusionBrief:
      "18-65 周岁；男女不限；面部皮肤干燥、肤色暗沉且研究者认为可通过水光注射改善；Fitzpatrick II-IV 型；同意维持现有护肤习惯，不使用其他相关美容治疗；自愿签署知情同意。",
    exclusionBrief: "以研究方案为准。",
    sponsor: null,
    intervention: "注射用透明质酸钠复合溶液（水光针）",
    studyDesign: "多中心临床试验",
    targetEnrollment: null,
    siteName:
      "广东省第二人民医院整形美容科 / 首都医科大学附属北京潞河医院整形外科 / 广州医科大学附属第二医院皮肤科 / 长沙市第三医院皮肤科 / 中山大学附属第一医院整形外科",
    siteAddress:
      "广州市海珠区新港中路 466 号；北京市通州区新华南路 82 号；广州市海珠区昌岗东路 250 号；湖南省长沙市天心区劳动西路 176 号；广东省广州市越秀区中山二路 58 号",
    contactPerson:
      "陈助理 18319741260（广东二）；白助理 18518291215（潞河）；李助理 18689241557（广医二）；李助理 15574248113（长沙三）；周助理 17875071607（中山一）",
    contactPhone: null,
    benefits: "研究治疗器械及相关检查免费；主任医师面诊；试验期间来院随访路程补助；购买临床试验保险。",
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获伦理委员会审查批准",
    qrcodeUrl: null,
  },
  {
    slug: "relugolix-prostate-cancer-chongqing2-2024",
    title: "瑞卢戈利片治疗雄激素敏感进展期前列腺癌招募",
    disease: "雄激素敏感进展期前列腺癌",
    city: "重庆",
    phase: null,
    status: "recruiting",
    isPublic: true,
    isFeatured: false,
    summary:
      "18 岁及以上、经组织学/细胞学确诊、需至少 24 周连续雄激素剥夺疗法的雄激素敏感进展期前列腺癌男性患者，参与重庆医科大学附属第二医院泌尿外科的瑞卢戈利片临床研究。",
    description:
      "申办方：江苏联环药业股份有限公司。\n主要评价指标：血清睾酮持续去势率。\n产品：瑞卢戈利片（120 mg）。",
    inclusionBrief:
      "年龄 ≥18 周岁，男性；组织学/细胞学确诊前列腺癌；雄激素敏感进展期（根治治疗后生化/临床复发且不适合挽救手术 / 新诊断雄激素敏感转移 / 局部进展期无法根治）；筛选时血清睾酮 ≥150 ng/dL；PSA >2.0 ng/mL 或根治切除后 >0.2 ng/mL 或放/冷冻/高强超治疗后高于干预后最小值 >2.0 ng/mL。",
    exclusionBrief: "以研究方案为准。",
    sponsor: "江苏联环药业股份有限公司",
    intervention: "瑞卢戈利片（120 mg）",
    studyDesign: "临床试验",
    targetEnrollment: null,
    siteName: "重庆医科大学附属第二医院泌尿外科",
    siteAddress: null,
    contactPerson: "蔡老师 / 张老师",
    contactPhone: "15023263173 / 18580480681",
    benefits: null,
    followUpPlan: null,
    adVersion: null,
    adVersionDate: null,
    ethicsApproval: "已获本院伦理委员会批准",
    qrcodeUrl: null,
  },
];

async function main() {
  const dbUrl =
    process.env.DATABASE_URL ??
    (process.env.NODE_ENV === "production"
      ? (() => {
          throw new Error("DATABASE_URL is required in production");
        })()
      : "file:./dev.db");
  const adapter = new PrismaBetterSqlite3({ url: dbUrl });
  const prisma = new PrismaClient({ adapter });

  let created = 0;
  let updated = 0;
  for (const t of trials) {
    const existing = await prisma.clinicalTrial.findUnique({ where: { slug: t.slug } });
    await prisma.clinicalTrial.upsert({
      where: { slug: t.slug },
      update: t,
      create: t,
    });
    if (existing) updated += 1;
    else created += 1;
  }

  const total = await prisma.clinicalTrial.count();
  console.log(`✅ 第二批招募文件入库完成`);
  console.log(`   本次新增 ${created} 条、更新 ${updated} 条`);
  console.log(`   当前数据库 ClinicalTrial 总数：${total}`);

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
